version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing NPM source dependencies
      - npm install
      - echo Installing the Angular CLI
      - npm install -g @angular/cli
    build:
      commands:
        - echo Build started on `date`
        - ng build
        - echo Build completed on `date`
    post_build:
      commands:
        - echo Moving dist folder contetns to pre-configured S3 bucket
        - aws s3 sync --delete dist/my-ui s3://my-ui-bucket-munmu
        - echo dist folder contents successfully uploaded to bucket

artifacts:
  files:
    - '**/*'
  base-directory: 'dist*'
  discard-paths: yes